global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: grudinprost@gmail.com
    from: grudinprost@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: grudinprost@gmail.com
    auth_identity: grudinprost@gmail.com
    #auth_password: ************
    send_resolved: true
